-- ============================================================
-- SBG Portal — Extended Seed Data (50 members)
-- Run this AFTER supabase-schema.sql
-- ============================================================

-- Clear existing data
TRUNCATE TABLE "Member" CASCADE;
TRUNCATE TABLE "SchoolYear" CASCADE;

-- School Years
INSERT INTO "SchoolYear" (id, label, is_active) VALUES
  (gen_random_uuid(), '2024-2025', false),
  (gen_random_uuid(), '2025-2026', true)
ON CONFLICT (label) DO NOTHING;

-- ── APPROVED (30) ─────────────────────────────────────────────────────────────
INSERT INTO "Member" (id, student_number, full_name, email, scholar_email, year_level, section, course, gender, skills, why_join, expectations, status, sbg_id, school_year, created_at, updated_at) VALUES
  (gen_random_uuid(), '2023-00001-BN-0', 'Juan dela Cruz', 'juan@gmail.com', 'juan@iskolar.pup.edu.ph', 2, 'BSIT-2A', 'BSIT', 'Male', ARRAY['Cloud Computing','Web Development'], 'I want to learn AWS.', 'Hands-on experience.', 'approved', 'SBG-2025-0001-PUPBC', '2025-2026', now() - interval '30 days', now() - interval '25 days'),
  (gen_random_uuid(), '2023-00002-BN-0', 'Maria Santos', 'maria@gmail.com', 'maria@iskolar.pup.edu.ph', 3, 'BSCS-3B', 'BSCS', 'Female', ARRAY['Machine Learning / AI','Data Analytics'], 'Passionate about AI.', 'Collaborate on projects.', 'approved', 'SBG-2025-0002-PUPBC', '2025-2026', now() - interval '29 days', now() - interval '24 days'),
  (gen_random_uuid(), '2024-00003-BN-0', 'Carlo Reyes', 'carlo@gmail.com', 'carlo@iskolar.pup.edu.ph', 1, 'BSIT-1C', 'BSIT', 'Male', ARRAY['DevOps & CI/CD','Containers & Kubernetes'], 'Get into DevOps early.', 'Learn CI/CD pipelines.', 'approved', 'SBG-2025-0003-PUPBC', '2025-2026', now() - interval '28 days', now() - interval '23 days'),
  (gen_random_uuid(), '2022-00004-BN-0', 'Ana Villanueva', 'ana@gmail.com', 'ana@iskolar.pup.edu.ph', 4, 'BSCS-4A', 'BSCS', 'Female', ARRAY['Serverless','Networking'], 'Strengthen cloud knowledge.', 'Mentorship and exposure.', 'approved', 'SBG-2025-0004-PUPBC', '2025-2026', now() - interval '27 days', now() - interval '22 days'),
  (gen_random_uuid(), '2023-00005-BN-0', 'Paolo Mendoza', 'paolo@gmail.com', 'paolo@iskolar.pup.edu.ph', 2, 'BSIT-2B', 'BSIT', 'Male', ARRAY['Security','Cloud Computing'], 'Explore AWS security.', 'Gain certifications.', 'approved', 'SBG-2025-0005-PUPBC', '2025-2026', now() - interval '26 days', now() - interval '21 days'),
  (gen_random_uuid(), '2022-00006-BN-0', 'Bianca Torres', 'bianca@gmail.com', 'bianca@iskolar.pup.edu.ph', 4, 'BSCS-4B', 'BSCS', 'Female', ARRAY['Databases','Data Analytics'], 'Build data pipelines.', 'Learn data engineering.', 'approved', 'SBG-2025-0006-PUPBC', '2025-2026', now() - interval '25 days', now() - interval '20 days'),
  (gen_random_uuid(), '2024-00007-BN-0', 'Marco Garcia', 'marco@gmail.com', 'marco@iskolar.pup.edu.ph', 1, 'BSIT-1A', 'BSIT', 'Male', ARRAY['IoT','Cloud Computing'], 'Interested in IoT.', 'Work on IoT projects.', 'approved', 'SBG-2025-0007-PUPBC', '2025-2026', now() - interval '24 days', now() - interval '19 days'),
  (gen_random_uuid(), '2023-00008-BN-0', 'Sophia Lim', 'sophia@gmail.com', 'sophia@iskolar.pup.edu.ph', 2, 'BSCS-2C', 'BSCS', 'Female', ARRAY['Machine Learning / AI','Serverless'], 'Use AWS for research.', 'Learn ML tools on AWS.', 'approved', 'SBG-2025-0008-PUPBC', '2025-2026', now() - interval '23 days', now() - interval '18 days'),
  (gen_random_uuid(), '2022-00009-BN-0', 'Rafael Cruz', 'rafael@gmail.com', 'rafael@iskolar.pup.edu.ph', 4, 'BSIT-4A', 'BSIT', 'Male', ARRAY['Web Development','DevOps & CI/CD'], 'Build serverless apps.', 'Deploy real projects.', 'approved', 'SBG-2025-0009-PUPBC', '2025-2026', now() - interval '22 days', now() - interval '17 days'),
  (gen_random_uuid(), '2023-00010-BN-0', 'Isabella Ramos', 'isabella@gmail.com', 'isabella@iskolar.pup.edu.ph', 3, 'BSCS-3A', 'BSCS', 'Female', ARRAY['Cloud Computing','Security'], 'Explore cloud security.', 'Hands-on labs.', 'approved', 'SBG-2025-0010-PUPBC', '2025-2026', now() - interval '21 days', now() - interval '16 days'),
  (gen_random_uuid(), '2024-00011-BN-0', 'Diego Flores', 'diego@gmail.com', 'diego@iskolar.pup.edu.ph', 1, 'BSIT-1B', 'BSIT', 'Male', ARRAY['Mobile Development','Web Development'], 'Build mobile apps on AWS.', 'Learn Amplify.', 'approved', 'SBG-2025-0011-PUPBC', '2025-2026', now() - interval '20 days', now() - interval '15 days'),
  (gen_random_uuid(), '2023-00012-BN-0', 'Camille Navarro', 'camille@gmail.com', 'camille@iskolar.pup.edu.ph', 2, 'BSCS-2A', 'BSCS', 'Female', ARRAY['Data Analytics','Databases'], 'Analyze data with AWS.', 'Build dashboards.', 'approved', 'SBG-2025-0012-PUPBC', '2025-2026', now() - interval '19 days', now() - interval '14 days'),
  (gen_random_uuid(), '2022-00013-BN-0', 'Luis Castillo', 'luis@gmail.com', 'luis@iskolar.pup.edu.ph', 4, 'BSIT-4B', 'BSIT', 'Male', ARRAY['Containers & Kubernetes','DevOps & CI/CD'], 'Master containerization.', 'Deploy with EKS.', 'approved', 'SBG-2025-0013-PUPBC', '2025-2026', now() - interval '18 days', now() - interval '13 days'),
  (gen_random_uuid(), '2023-00014-BN-0', 'Gabrielle Morales', 'gabrielle@gmail.com', 'gabrielle@iskolar.pup.edu.ph', 3, 'BSCS-3C', 'BSCS', 'Female', ARRAY['Serverless','Cloud Computing'], 'Build serverless APIs.', 'Learn Lambda and API Gateway.', 'approved', 'SBG-2025-0014-PUPBC', '2025-2026', now() - interval '17 days', now() - interval '12 days'),
  (gen_random_uuid(), '2024-00015-BN-0', 'Nathan Aquino', 'nathan@gmail.com', 'nathan@iskolar.pup.edu.ph', 1, 'BSIT-1D', 'BSIT', 'Male', ARRAY['Cloud Computing','Networking'], 'Start cloud journey early.', 'Get AWS certified.', 'approved', 'SBG-2025-0015-PUPBC', '2025-2026', now() - interval '16 days', now() - interval '11 days'),
  (gen_random_uuid(), '2023-00016-BN-0', 'Alicia Reyes', 'alicia@gmail.com', 'alicia@iskolar.pup.edu.ph', 2, 'BSCS-2B', 'BSCS', 'Female', ARRAY['Machine Learning / AI','Cloud Computing'], 'Apply ML in real projects.', 'Use SageMaker.', 'approved', 'SBG-2025-0016-PUPBC', '2025-2026', now() - interval '15 days', now() - interval '10 days'),
  (gen_random_uuid(), '2022-00017-BN-0', 'Kevin Santos', 'kevin@gmail.com', 'kevin@iskolar.pup.edu.ph', 4, 'BSIT-4C', 'BSIT', 'Male', ARRAY['Security','Networking'], 'Specialize in cloud security.', 'Learn IAM and GuardDuty.', 'approved', 'SBG-2025-0017-PUPBC', '2025-2026', now() - interval '14 days', now() - interval '9 days'),
  (gen_random_uuid(), '2023-00018-BN-0', 'Patricia dela Rosa', 'patricia@gmail.com', 'patricia@iskolar.pup.edu.ph', 3, 'BSCS-3B', 'BSCS', 'Female', ARRAY['Web Development','Serverless'], 'Build full-stack apps.', 'Deploy on AWS Amplify.', 'approved', 'SBG-2025-0018-PUPBC', '2025-2026', now() - interval '13 days', now() - interval '8 days'),
  (gen_random_uuid(), '2024-00019-BN-0', 'Ethan Bautista', 'ethan@gmail.com', 'ethan@iskolar.pup.edu.ph', 1, 'BSIT-1A', 'BSIT', 'Male', ARRAY['IoT','Serverless'], 'Connect devices to cloud.', 'Build IoT solutions.', 'approved', 'SBG-2025-0019-PUPBC', '2025-2026', now() - interval '12 days', now() - interval '7 days'),
  (gen_random_uuid(), '2023-00020-BN-0', 'Nicole Fernandez', 'nicole@gmail.com', 'nicole@iskolar.pup.edu.ph', 2, 'BSCS-2D', 'BSCS', 'Female', ARRAY['Data Analytics','Machine Learning / AI'], 'Work on data science.', 'Use AWS data tools.', 'approved', 'SBG-2025-0020-PUPBC', '2025-2026', now() - interval '11 days', now() - interval '6 days'),
  (gen_random_uuid(), '2022-00021-BN-0', 'Adrian Gonzales', 'adrian@gmail.com', 'adrian@iskolar.pup.edu.ph', 4, 'BSIT-4A', 'BSIT', 'Male', ARRAY['DevOps & CI/CD','Containers & Kubernetes'], 'Automate deployments.', 'Master CI/CD on AWS.', 'approved', 'SBG-2025-0021-PUPBC', '2025-2026', now() - interval '10 days', now() - interval '5 days'),
  (gen_random_uuid(), '2023-00022-BN-0', 'Samantha Ocampo', 'samantha@gmail.com', 'samantha@iskolar.pup.edu.ph', 3, 'BSCS-3A', 'BSCS', 'Female', ARRAY['Cloud Computing','Databases'], 'Manage cloud databases.', 'Learn RDS and DynamoDB.', 'approved', 'SBG-2025-0022-PUPBC', '2025-2026', now() - interval '9 days', now() - interval '4 days'),
  (gen_random_uuid(), '2024-00023-BN-0', 'Joshua Dela Cruz', 'joshua@gmail.com', 'joshua@iskolar.pup.edu.ph', 1, 'BSIT-1C', 'BSIT', 'Male', ARRAY['Web Development','Cloud Computing'], 'Host web apps on AWS.', 'Learn EC2 and S3.', 'approved', 'SBG-2025-0023-PUPBC', '2025-2026', now() - interval '8 days', now() - interval '3 days'),
  (gen_random_uuid(), '2023-00024-BN-0', 'Angelica Tan', 'angelica@gmail.com', 'angelica@iskolar.pup.edu.ph', 2, 'BSCS-2A', 'BSCS', 'Female', ARRAY['Security','Cloud Computing'], 'Secure cloud workloads.', 'Learn AWS security best practices.', 'approved', 'SBG-2025-0024-PUPBC', '2025-2026', now() - interval '7 days', now() - interval '2 days'),
  (gen_random_uuid(), '2022-00025-BN-0', 'Christian Villanueva', 'christian@gmail.com', 'christian@iskolar.pup.edu.ph', 4, 'BSIT-4B', 'BSIT', 'Male', ARRAY['Serverless','DevOps & CI/CD'], 'Build scalable systems.', 'Use Lambda and CodePipeline.', 'approved', 'SBG-2025-0025-PUPBC', '2025-2026', now() - interval '6 days', now() - interval '1 day'),
  (gen_random_uuid(), '2023-00026-BN-0', 'Jasmine Reyes', 'jasmine@gmail.com', 'jasmine@iskolar.pup.edu.ph', 3, 'BSCS-3C', 'BSCS', 'Female', ARRAY['Mobile Development','Cloud Computing'], 'Build mobile backends.', 'Use AWS AppSync.', 'approved', 'SBG-2025-0026-PUPBC', '2025-2026', now() - interval '5 days', now() - interval '1 day'),
  (gen_random_uuid(), '2024-00027-BN-0', 'Ryan Mendoza', 'ryan@gmail.com', 'ryan@iskolar.pup.edu.ph', 1, 'BSIT-1B', 'BSIT', 'Male', ARRAY['Networking','Cloud Computing'], 'Learn cloud networking.', 'Understand VPC and Route53.', 'approved', 'SBG-2025-0027-PUPBC', '2025-2026', now() - interval '4 days', now() - interval '1 day'),
  (gen_random_uuid(), '2023-00028-BN-0', 'Kristine Lim', 'kristine@gmail.com', 'kristine@iskolar.pup.edu.ph', 2, 'BSCS-2B', 'BSCS', 'Female', ARRAY['Data Analytics','Databases'], 'Work with big data.', 'Use Redshift and Athena.', 'approved', 'SBG-2025-0028-PUPBC', '2025-2026', now() - interval '3 days', now() - interval '1 day'),
  (gen_random_uuid(), '2022-00029-BN-0', 'Mark Aquino', 'mark@gmail.com', 'mark@iskolar.pup.edu.ph', 4, 'BSIT-4C', 'BSIT', 'Male', ARRAY['Machine Learning / AI','Data Analytics'], 'Apply AI in final year project.', 'Use Rekognition and Comprehend.', 'approved', 'SBG-2025-0029-PUPBC', '2025-2026', now() - interval '2 days', now() - interval '1 day'),
  (gen_random_uuid(), '2023-00030-BN-0', 'Denise Castro', 'denise@gmail.com', 'denise@iskolar.pup.edu.ph', 3, 'BSCS-3B', 'BSCS', 'Female', ARRAY['IoT','Cloud Computing'], 'Build smart systems.', 'Use AWS IoT Core.', 'approved', 'SBG-2025-0030-PUPBC', '2025-2026', now() - interval '1 day', now()),

-- ── PENDING (10) ──────────────────────────────────────────────────────────────
  (gen_random_uuid(), '2024-00031-BN-0', 'Miguel Torres', 'miguel@gmail.com', 'miguel@iskolar.pup.edu.ph', 1, 'BSIT-1A', 'BSIT', 'Male', ARRAY['IoT','Cloud Computing'], 'Interested in IoT.', 'Work on IoT projects.', 'pending', NULL, NULL, now() - interval '5 hours', now() - interval '5 hours'),
  (gen_random_uuid(), '2023-00032-BN-0', 'Sofia Bautista', 'sofia@gmail.com', 'sofia@iskolar.pup.edu.ph', 2, 'BSCS-2C', 'BSCS', 'Female', ARRAY['Data Analytics','Machine Learning / AI'], 'Build data pipelines.', 'Learn data engineering.', 'pending', NULL, NULL, now() - interval '4 hours', now() - interval '4 hours'),
  (gen_random_uuid(), '2024-00033-BN-0', 'Lance Navarro', 'lance@gmail.com', 'lance@iskolar.pup.edu.ph', 1, 'BSIT-1D', 'BSIT', 'Male', ARRAY['Web Development','Serverless'], 'Build web apps.', 'Learn modern deployment.', 'pending', NULL, NULL, now() - interval '3 hours', now() - interval '3 hours'),
  (gen_random_uuid(), '2023-00034-BN-0', 'Trisha Morales', 'trisha@gmail.com', 'trisha@iskolar.pup.edu.ph', 2, 'BSCS-2D', 'BSCS', 'Female', ARRAY['Security','Networking'], 'Learn cloud security.', 'Get AWS certified.', 'pending', NULL, NULL, now() - interval '2 hours', now() - interval '2 hours'),
  (gen_random_uuid(), '2024-00035-BN-0', 'Nico Flores', 'nico@gmail.com', 'nico@iskolar.pup.edu.ph', 1, 'BSIT-1B', 'BSIT', 'Male', ARRAY['Cloud Computing','DevOps & CI/CD'], 'Start cloud journey.', 'Learn DevOps practices.', 'pending', NULL, NULL, now() - interval '90 minutes', now() - interval '90 minutes'),
  (gen_random_uuid(), '2023-00036-BN-0', 'Alyssa Gonzales', 'alyssa@gmail.com', 'alyssa@iskolar.pup.edu.ph', 3, 'BSCS-3A', 'BSCS', 'Female', ARRAY['Machine Learning / AI','Cloud Computing'], 'Apply ML in projects.', 'Use SageMaker.', 'pending', NULL, NULL, now() - interval '60 minutes', now() - interval '60 minutes'),
  (gen_random_uuid(), '2024-00037-BN-0', 'Zach Dela Cruz', 'zach@gmail.com', 'zach@iskolar.pup.edu.ph', 1, 'BSIT-1C', 'BSIT', 'Male', ARRAY['Containers & Kubernetes','DevOps & CI/CD'], 'Learn containerization.', 'Deploy with ECS.', 'pending', NULL, NULL, now() - interval '45 minutes', now() - interval '45 minutes'),
  (gen_random_uuid(), '2023-00038-BN-0', 'Mia Santos', 'mia@gmail.com', 'mia@iskolar.pup.edu.ph', 2, 'BSCS-2A', 'BSCS', 'Female', ARRAY['Databases','Data Analytics'], 'Manage cloud databases.', 'Learn DynamoDB.', 'pending', NULL, NULL, now() - interval '30 minutes', now() - interval '30 minutes'),
  (gen_random_uuid(), '2024-00039-BN-0', 'Jared Reyes', 'jared@gmail.com', 'jared@iskolar.pup.edu.ph', 1, 'BSIT-1A', 'BSIT', 'Male', ARRAY['Networking','Cloud Computing'], 'Understand cloud networking.', 'Learn VPC.', 'pending', NULL, NULL, now() - interval '15 minutes', now() - interval '15 minutes'),
  (gen_random_uuid(), '2023-00040-BN-0', 'Ella Tan', 'ella@gmail.com', 'ella@iskolar.pup.edu.ph', 2, 'BSCS-2B', 'BSCS', 'Female', ARRAY['Web Development','Mobile Development'], 'Build cross-platform apps.', 'Use AWS Amplify.', 'pending', NULL, NULL, now() - interval '5 minutes', now() - interval '5 minutes'),

-- ── REJECTED (5) ──────────────────────────────────────────────────────────────
  (gen_random_uuid(), '2023-00041-BN-0', 'Ramon Garcia', 'ramon@gmail.com', 'ramon@iskolar.pup.edu.ph', 3, 'BSIT-3A', 'BSIT', 'Male', ARRAY['Security','Networking'], 'Cybersecurity passion.', 'Gain security labs.', 'rejected', NULL, NULL, now() - interval '20 days', now() - interval '18 days'),
  (gen_random_uuid(), '2022-00042-BN-0', 'Carla Ocampo', 'carla@gmail.com', 'carla@iskolar.pup.edu.ph', 4, 'BSCS-4C', 'BSCS', 'Female', ARRAY['Cloud Computing'], 'Explore cloud.', 'Learn basics.', 'rejected', NULL, NULL, now() - interval '18 days', now() - interval '16 days'),
  (gen_random_uuid(), '2023-00043-BN-0', 'Felix Castillo', 'felix@gmail.com', 'felix@iskolar.pup.edu.ph', 3, 'BSIT-3B', 'BSIT', 'Male', ARRAY['Web Development'], 'Build websites.', 'Host on AWS.', 'rejected', NULL, NULL, now() - interval '15 days', now() - interval '13 days'),
  (gen_random_uuid(), '2024-00044-BN-0', 'Hanna Cruz', 'hanna@gmail.com', 'hanna@iskolar.pup.edu.ph', 1, 'BSCS-1A', 'BSCS', 'Female', ARRAY['Cloud Computing','Databases'], 'Learn cloud databases.', 'Use RDS.', 'rejected', NULL, NULL, now() - interval '12 days', now() - interval '10 days'),
  (gen_random_uuid(), '2023-00045-BN-0', 'Ivan Ramos', 'ivan@gmail.com', 'ivan@iskolar.pup.edu.ph', 2, 'BSIT-2C', 'BSIT', 'Male', ARRAY['DevOps & CI/CD'], 'Automate workflows.', 'Use CodePipeline.', 'rejected', NULL, NULL, now() - interval '10 days', now() - interval '8 days'),

-- ── INACTIVE (5) ──────────────────────────────────────────────────────────────
  (gen_random_uuid(), '2022-00046-BN-0', 'Lea Mendoza', 'lea@gmail.com', 'lea@iskolar.pup.edu.ph', 4, 'BSIT-4B', 'BSIT', 'Female', ARRAY['Web Development','Serverless'], 'Build serverless apps.', 'Deploy real projects.', 'inactive', 'SBG-2024-0001-PUPBC', '2024-2025', now() - interval '400 days', now() - interval '30 days'),
  (gen_random_uuid(), '2021-00047-BN-0', 'Jerome Bautista', 'jerome@gmail.com', 'jerome@iskolar.pup.edu.ph', 4, 'BSCS-4A', 'BSCS', 'Male', ARRAY['Cloud Computing','DevOps & CI/CD'], 'Master cloud.', 'Get certified.', 'inactive', 'SBG-2024-0002-PUPBC', '2024-2025', now() - interval '380 days', now() - interval '30 days'),
  (gen_random_uuid(), '2021-00048-BN-0', 'Vanessa Lim', 'vanessa@gmail.com', 'vanessa@iskolar.pup.edu.ph', 4, 'BSIT-4A', 'BSIT', 'Female', ARRAY['Data Analytics','Databases'], 'Work with data.', 'Use Redshift.', 'inactive', 'SBG-2024-0003-PUPBC', '2024-2025', now() - interval '360 days', now() - interval '30 days'),
  (gen_random_uuid(), '2021-00049-BN-0', 'Arnold Fernandez', 'arnold@gmail.com', 'arnold@iskolar.pup.edu.ph', 4, 'BSCS-4B', 'BSCS', 'Male', ARRAY['Machine Learning / AI','Cloud Computing'], 'Apply AI.', 'Use SageMaker.', 'inactive', 'SBG-2024-0004-PUPBC', '2024-2025', now() - interval '340 days', now() - interval '30 days'),
  (gen_random_uuid(), '2021-00050-BN-0', 'Rowena Castro', 'rowena@gmail.com', 'rowena@iskolar.pup.edu.ph', 4, 'BSIT-4C', 'BSIT', 'Female', ARRAY['Security','Networking'], 'Secure cloud systems.', 'Learn IAM.', 'inactive', 'SBG-2024-0005-PUPBC', '2024-2025', now() - interval '320 days', now() - interval '30 days');
